class{"dpm::head_disknode":
   configure_default_pool => true,
   configure_default_filesystem => true,
   disk_nodes => ['localhost'],
   localdomain => "cern.ch",
   db_pass => "MYSQLPASS",
   mysql_root_pass => "PASS",
   token_password => "TOKEN_PASSWORD",
   xrootd_sharedkey => "A32TO64CHARACTERKEYTESTTESTTESTTEST",
   site_name => "CERN_DPM_TEST",
   volist  => ['dteam', 'lhcb'],
   mountpoints => ['/srv/dpm','/srv/dpm/01'],
   pools => ['mypool:100M'],
   filesystems => ["mypool:${fqdn}:/srv/dpm/01"],
}
